# -*- coding: utf-8 -*-
"""chart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQQzL_Kd8PZ7Zs8EQZ27bzDNi5Ia2G27
"""

import pandas as pd

# 그래프 데이터 생성
def make_chart_data(config, start_date, end_date, forecast_result):
    pred_df = pd.read_csv(config["prediction_path"])

    pred_df[config["date_col"]] = pd.to_datetime(pred_df[config["date_col"]])
    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)

    # 조회 기간 데이터 필터링
    chart_df = pred_df[
        (pred_df[config["date_col"]] >= start_date) &
        (pred_df[config["date_col"]] <= end_date)
    ].copy()

    chart_data = []

    # 실제 수요 데이터 생성
    for _, row in chart_df.iterrows():
        chart_data.append({
            "date": row[config["date_col"]].strftime("%Y-%m"),
            "actual_demand": int(round(row["actual_demand"])),
            "forecast_demand": int(round(row["predicted_demand"]))
        })

    # 다음 달 예측 데이터 추가
    chart_data.append({
        "date": forecast_result["forecast_month"],
        "actual_demand": None,
        "forecast_demand": int(round(forecast_result["national_forecast_demand"]))
    })

    return chart_data