# -*- coding: utf-8 -*-
"""config_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbNa3rqxMhp-PZGsFvIbV8yQUim6Glt9
"""

import yaml

def load_item_config(item_code) :
    with open("configs/items.yaml", "r", encoding = "utf-8") as f:
        configs = yaml.safe_load(f)

    return configs[item_code]