# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGrKKP76G77dybERiMAbTKj66kWn8gVa
"""
import pandas as pd

def load_train_data(config) :
    df = pd.read_csv(config["train_data_path"])
    df[config["date_col"]] = pd.to_datetime(df[config["date_col"]])
    return df

def load_raw_data(config) :
    df = pd.read_csv(config["raw_data_path"])
    df[config["date_col"]] = pd.to_datetime(df[config["date_col"]])
    return df