# -*- coding: utf-8 -*-
"""inventory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16EwGdTIrnluCm1x0HnfqTZu-iahKUe-8
"""

def calculate_inventory_status(config, raw_df, train_df, national_forecast_demand) :

    # 원본 데이터
    latest_raw = raw_df.sort_values(config["date_col"]).iloc[-1]
    
    # 전국 최근 재고량
    national_current_stock = latest_raw[config["stock_col"]]

    # 최근 12개월 수요 표준편차
    recent_std = train_df[config["demand_col"]].tail(12).std()

    # 전국 안전재고
    national_safety_stock = 1.65 * recent_std

    # 전국 부족 예상 수량
    national_shortage_qty = max((national_forecast_demand + national_safety_stock) - national_current_stock, 0)

    return {
        "national_current_stock": int(round(float(national_current_stock))),
        "national_safety_stock": int(round(float(national_safety_stock))),
        "national_shortage_qty": int(round(float(national_shortage_qty)))
    }