# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jh6W1jhrW8x6b0E0aHFXZnsDWtyzDXqD
"""

import joblib
import pandas as pd

def forecast_next_month(config, train_df, raw_df) :

    # 모델 로드
    model = joblib.load(config["model_path"])

    # 변수 로드
    features = joblib.load(config["features_path"])

    # 최근 학습 데이터 추출
    latest_train = train_df.sort_values(config["date_col"]).iloc[[-1]]

    # 최근 원본 데이터 추출
    latest_raw = raw_df.sort_values(config["date_col"]).iloc[[-1]]

    # 예측 데이터 생성
    X_latest = latest_train[features]

    # 다음 달 증감률 예측
    national_forecast_change_rate = model.predict(X_latest)[0]

    # 최근 수요
    national_current_demand = latest_raw[config["demand_col"]].iloc[0]

    # 예측 수요량 계산(증감률 역산)
    national_forecast_demand = national_current_demand * (1 + national_forecast_change_rate / 100)

    # 예측 대상 월 생성
    forecast_month = latest_raw[config["date_col"]].iloc[0] + pd.DateOffset(months=1)

    return {
        "forecast_month": forecast_month.strftime("%Y-%m"),
        "national_forecast_change_rate": round(float(national_forecast_change_rate), 2),
        "national_forecast_demand": int(round(national_forecast_demand))
    }