# -*- coding: utf-8 -*-
"""service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3AiSp1huqLM8NCA-9FU32gVZ7ef3nwG
"""

import json
import pandas as pd

from src.config_loader import load_item_config
from src.data_loader import load_train_data, load_raw_data
from src.predict import forecast_next_month
from src.inventory import calculate_inventory_status
from src.chart import make_chart_data
from src.company_plan import calculate_company_plan
from src.risk_analysis import make_risk_analysis, extract_industry_importance
from src.feature_names import get_feature_display_name

def load_importance(config, top_n=5):
    importance_df = pd.read_csv(config["importance_path"])

    if "display_name" not in importance_df.columns:
        importance_df["display_name"] = importance_df["feature"].apply(
            get_feature_display_name
        )

    importance_df["importance"] = importance_df["importance"].round(2)

    importance_df = importance_df.sort_values(
        by="importance",
        ascending=False
    ).head(top_n)

    return importance_df.to_dict(orient="records")


def load_metrics(config):
    with open(config["metrics_path"], "r", encoding="utf-8") as f:
        return json.load(f)


def get_item_result(item_code, start_date, end_date) :

    # 품목 설정 정보 로드
    config = load_item_config(item_code)

    # 학습 및 원본 데이터
    train_df = load_train_data(config)
    raw_df = load_raw_data(config)

    # 다음 달 수요 예측
    forecast_result = forecast_next_month(config, train_df, raw_df)

    chart_data = make_chart_data(
        config = config,
        start_date = start_date,
        end_date = end_date,
        forecast_result = forecast_result
    )
    
    # 모델 성능 지표
    metrics = load_metrics(config)

    # 변수 중요도
    importance = load_importance(config)[:5]

    # 전국 기준 재고 상태
    inventory_status = calculate_inventory_status(
        config = config,
        raw_df = raw_df,
        train_df = train_df,
        national_forecast_demand = forecast_result["national_forecast_demand"]
    )

    # 주요 영향 산업
    main_industries = extract_industry_importance(
        config["importance_path"],
        top_n = 3
    )

    # 전국 기준 위험도 분석
    risk_analysis = make_risk_analysis(
        forecast_month = forecast_result["forecast_month"],
        national_current_stock = inventory_status["national_current_stock"],
        national_forecast_demand = forecast_result["national_forecast_demand"],
        national_shortage_qty = inventory_status["national_shortage_qty"],
        main_industries = main_industries
    )

    return {
        "item_code": item_code,
        "item_name": config["name"],
        "forecast_month": forecast_result["forecast_month"],

        "national_forecast": forecast_result,
        "inventory_status": inventory_status,
        "risk_analysis": risk_analysis,

        "model_info": metrics,
        "feature_importance": importance,
        "chart_data": chart_data
    }

# 자사 생산/재고 가이드라인 생성
def get_company_guideline(
    item_code,
    company_stock,
    lead_time,
    market_share = None,
    shipment_history = None,
    demand_volatility_rate = None,
    demand_std = None,
    share_period = 12,
    std_period = 12,
    yield_rate = 100,
    service_level = 95,
    max_capacity = None,
    lot_size = None
) :
    config = load_item_config(item_code)

    train_df = load_train_data(config)
    raw_df = load_raw_data(config)

    forecast_result = forecast_next_month(config, train_df, raw_df)

    # 최근 전국 수요 데이터 - 출하량 기반 점유율 추정
    national_demand_history = (
        raw_df
        .sort_values(config["date_col"])[config["demand_col"]]
        .tail(share_period)
        .tolist()
    )

    production_guideline = calculate_company_plan(
    national_forecast_demand=forecast_result["national_forecast_demand"],
    company_stock=company_stock,
    lead_time=lead_time,

    national_demand_history=national_demand_history,
    company_market_share=market_share,
    company_shipment_history=shipment_history,

    company_demand_volatility_rate=demand_volatility_rate,
    company_demand_std=demand_std,

    share_period=share_period,
    std_period=std_period,
    yield_rate=yield_rate,
    service_level=service_level,
    max_capacity=max_capacity,
    lot_size=lot_size
)

    return {
        "item_code": item_code,
        "item_name": config["name"],
        "forecast_month": forecast_result["forecast_month"],

        "national_forecast_demand": forecast_result["national_forecast_demand"],
        "national_forecast_change_rate": forecast_result["national_forecast_change_rate"],

        "production_guideline": production_guideline
    }